# Generated by Django 4.2.29 on 2026-03-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_eventoutbox_event_type'),
        ('sync', '0002_eventsource_fields'),
    ]

    operations = [
    ]
