# Generated by Django 4.2.29 on 2026-04-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_merge_20260331_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoutbox',
            name='event_type',
            field=models.CharField(choices=[('member.insert', '회원 신규'), ('member.update', '회원 수정'), ('payment.insert', '결제 신규'), ('business.insert', '업체 신규'), ('business.update', '업체 수정'), ('company.insert', '채용회사 신규'), ('company.update', '채용회사 수정'), ('recruit.insert', '채용공고 신규'), ('recruit.update', '채용공고 수정'), ('job_seeker.insert', '구직자 신규'), ('job_seeker.update', '구직자 수정')], db_index=True, max_length=50, verbose_name='이벤트 유형'),
        ),
    ]
