# Generated by Django 4.2.29 on 2026-04-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business114', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
    ]
