# Generated by Django 4.2.29 on 2026-04-07 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': '결제내역', 'verbose_name_plural': '결제내역 목록'},
        ),
        migrations.AlterModelOptions(
            name='pointaccount',
            options={'verbose_name': '포인트계정', 'verbose_name_plural': '포인트계정 목록'},
        ),
        migrations.RemoveIndex(
            model_name='paymenthistory',
            name='member_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenthistory',
            name='tid_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenthistory',
            name='status_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointaccount',
            name='member_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenthistory',
            new_name='idx_payment_danal_order',
            old_name='danal_order_id_idx',
        ),
        migrations.RemoveField(
            model_name='pointaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pointaccount',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.IntegerField(verbose_name='결제금액'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인일시'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='danal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='다날주문번호'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='danal_response',
            field=models.JSONField(blank=True, null=True, verbose_name='다날원본응답'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='error_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='에러코드'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='에러메시지'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='성공여부'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='mysql_synced',
            field=models.BooleanField(default=False, verbose_name='MySQL동기화여부'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='pay_method',
            field=models.CharField(choices=[('card', '카드'), ('bank', '무통장입금'), ('direct_bank', '실시간계좌이체')], max_length=30, verbose_name='결제방법'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='point_amount',
            field=models.IntegerField(verbose_name='충전포인트'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='result_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='결과코드'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='result_message',
            field=models.CharField(blank=True, max_length=200, verbose_name='결과메시지'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거절'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='결제상태'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='tid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='다날거래번호(TID)'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='pointaccount',
            name='last_charged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막충전일시'),
        ),
        migrations.AlterField(
            model_name='pointaccount',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막사용일시'),
        ),
        migrations.AlterField(
            model_name='pointaccount',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_account', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='pointaccount',
            name='total_charged',
            field=models.BigIntegerField(default=0, verbose_name='총충전포인트'),
        ),
        migrations.AlterField(
            model_name='pointaccount',
            name='total_used',
            field=models.BigIntegerField(default=0, verbose_name='총사용포인트'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['member', 'is_success'], name='idx_payment_member_success'),
        ),
    ]
